# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 2
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: bottleneck
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Este issue ha sido marcado automáticamente como "bottleneck" porque no ha tenido actividad reciente. El issue sera cerrado si no ocurre alguna actividad en el issue.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
